<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e3b92dd0-48d3-4177-b14c-c5887e9974b8</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_99</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/main[1]/div[2]/div[2]/div[1]/div[2]/div[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>