<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>197f2514-172a-46b6-9d79-d8b103248aec</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_95</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/main[1]/div[2]/div[2]/div[1]/div[1]/div[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>