<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c50f9fb2-f433-49de-b172-d6a9550c9004</elementGuidId>
    <imagePath></imagePath>
    <name>canvas_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/canvas[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>