<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1b606f3e-1ad2-4a49-bda0-45e77a56f12e</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_46</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/main[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/div[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>